//UNIT
export const FIND_ALL_UNIT = "FIND_ALL_UNIT"
export const FIND_ALL_UNIT_SUCCESS = "FIND_ALL_UNIT_SUCCESS"
export const FIND_ALL_UNIT_FAILURE = "FIND_ALL_UNIT_FAILURE"

export const FIND_UNIT_BY_ID = "FIND_UNIT_BY_ID"
export const FIND_UNIT_BY_ID_SUCCESS = "FIND_UNIT_BY_ID_SUCCESS"
export const FIND_UNIT_BY_ID_FAILURE = "FIND_UNIT_BY_ID_FAILURE"

export const SAVE_UNIT = "SAVE_UNIT"
export const SAVE_UNIT_SUCCESS = "SAVE_UNIT_SUCCESS"
export const SAVE_UNIT_FAILURE = "SAVE_UNIT_FAILURE"

export const REMOVE_UNIT_BY_ID = "REMOVE_UNIT_BY_ID"
export const REMOVE_UNIT_BY_ID_SUCCESS = "REMOVE_UNIT_BY_ID_SUCCESS"
export const REMOVE_UNIT_BY_ID_FAILURE = "REMOVE_UNIT_BY_ID_FAILURE"


//ITEM
export const FIND_ALL_ITEM = "FIND_ALL_ITEM"
export const FIND_ALL_ITEM_SUCCESS = "FIND_ALL_ITEM_SUCCESS"
export const FIND_ALL_ITEM_FAILURE = "FIND_ALL_ITEM_FAILURE"

export const FIND_ITEM_BY_ID = "FIND_ITEM_BY_ID"
export const FIND_ITEM_BY_ID_SUCCESS = "FIND_ITEM_BY_ID_SUCCESS"
export const FIND_ITEM_BY_ID_FAILURE = "FIND_ITEM_BY_ID_FAILURE"

export const SAVE_ITEM = "SAVE_ITEM"
export const SAVE_ITEM_SUCCESS = "SAVE_ITEM_SUCCESS"
export const SAVE_ITEM_FAILURE = "SAVE_ITEM_FAILURE"

export const REMOVE_ITEM_BY_ID = "REMOVE_ITEM_BY_ID"
export const REMOVE_ITEM_BY_ID_SUCCESS = "REMOVE_ITEM_BY_ID_SUCCESS"
export const REMOVE_ITEM_BY_ID_FAILURE = "REMOVE_ITEM_BY_ID_FAILURE"

export const UPLOAD_ITEM_BY_ID = "UPLOAD_ITEM_BY_ID"
export const UPLOAD_ITEM_BY_ID_SUCCESS = "UPLOAD_ITEM_BY_ID_SUCCESS"
export const UPLOAD_ITEM_BY_ID_FAILURE = "UPLOAD_ITEM_BY_ID_FAILURE"

//STOCK
export const FIND_ALL_STOCK = "FIND_ALL_STOCK"
export const FIND_ALL_STOCK_SUCCESS = "FIND_ALL_STOCK_SUCCESS"
export const FIND_ALL_STOCK_FAILURE = "FIND_ALL_STOCK_FAILURE"

export const FIND_STOCK_BY_ID = "FIND_STOCK_BY_ID"
export const FIND_STOCK_BY_ID_SUCCESS = "FIND_STOCK_BY_ID_SUCCESS"
export const FIND_STOCK_BY_ID_FAILURE = "FIND_STOCK_BY_ID_FAILURE"

export const SAVE_STOCK = "SAVE_STOCK"
export const SAVE_STOCK_SUCCESS = "SAVE_STOCK_SUCCESS"
export const SAVE_STOCK_FAILURE = "SAVE_STOCK_FAILURE"

export const REMOVE_STOCK_BY_ID = "REMOVE_STOCK_BY_ID"
export const REMOVE_STOCK_BY_ID_SUCCESS = "REMOVE_STOCK_BY_ID_SUCCESS"
export const REMOVE_STOCK_BY_ID_FAILURE = "REMOVE_STOCK_BY_ID_FAILURE"